package com.example.demo.model;

import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import javax.persistence.*;

@Entity
@Data
@NoArgsConstructor
@ToString
public class Laptop {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    private String model;
    private Double price;
    // the table with the mappedBy is the secondary table.
    // since owns here, will show up as OWNS_ID column if no @JoinColumn name.
    @OneToOne(mappedBy = "owns")
    private Student belongsTo;

    public Laptop(String model, Double price) {
        // do not include id, want it to be generated by Spring.
        this.model = model;
        this.price = price;
    }


}
